import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const neurialGrotesk = localFont({
  src: [
    {
      path: "../../public/fonts/neurial-grotesk/neurial-grotesk-light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/neurial-grotesk/neurial-grotesk-regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/neurial-grotesk/neurial-grotesk-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/neurial-grotesk/neurial-grotesk-bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-heading",
});

const openSans = Open_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${neurialGrotesk.variable} ${openSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
