import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const neurialGrotesk = localFont({
  src: [
    {
      path: "../../public/fonts/neurial-grotesk/neurial-grotesk-light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/neurial-grotesk/neurial-grotesk-regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/neurial-grotesk/neurial-grotesk-medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/neurial-grotesk/neurial-grotesk-bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-heading",
});

const openSans = Open_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const schema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "name": "TicketDot Technologies Private Limited",
      "url": "https://ticketdot.in",
      "logo": "https://ticketdot.in/logo.png",
      "description": "TicketDot is a smart mobility platform providing QR-based bus ticketing, student pass management,",
      "sameAs": [
        "https://www.linkedin.com/company/ticketdot",
        "https://www.instagram.com/ticketdot"
      ]
    },
    {
      "@type": "SoftwareApplication",
      "name": "TicketDot",
      "applicationCategory": "BusinessApplication",
      "operatingSystem": "iOS, Android, Web",
      "url": "https://ticketdot.in",
      "description": "TicketDot enables QR-based ticketing, digital passes, payment integration, and transport operator management.",
      "provider": {
        "@type": "Organization",
        "name": "TicketDot Technologies Private Limited"
      }
    },
    {
      "@type": "FAQPage",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "What is TicketDot?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "TicketDot is a smart mobility platform that digitizes ticketing for buses, student passes"
          }
        },
        {
          "@type": "Question",
          "name": "How does TicketDot bus ticketing work?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Passengers scan a QR code, select source and destination, pay digitally, and receive a digital ticket."
          }
        },
        {
          "@type": "Question",
          "name": "Does TicketDot support UPI payments?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes, TicketDot supports digital payments through integrated payment gateways and UPI."
          }
        },
        {
          "@type": "Question",
          "name": "Can private bus operators use TicketDot?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes, TicketDot is designed for private bus operators, transport companies, and mobility providers."
          }
        }
      ]
    }
  ]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${neurialGrotesk.variable} ${openSans.variable}`}>
      <head>
        {/* Google Tag Manager */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NN672HNV');`,
          }}
        />
        {/* End Google Tag Manager */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(schema),
          }}
        />
      </head>
      <body>
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-NN672HNV"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        {/* End Google Tag Manager (noscript) */}
        {children}
      </body>
    </html>
  );
}
